### ISSUE TITLE
eventsource needs to escape messages

### ISSUE THREAD

**Issue by aronatkins** [igm/sockjs-go#100]
The EventSource frame writer does no escaping of its messages:
https://github.com/igm/sockjs-go/blob/f490575850cc1e456d2641a15dbae1924db6a1da/sockjs/eventsource.go#L31

Compare that to how sockjs-node handles its EventSource payload:
https://github.com/sockjs/sockjs-node/blob/9efed2c754226b702eb468ef0643b316b91bf37f/lib/transport/eventsource.js#L13-L17

This has caused a problem in our update from sockjs-client-0.3.4 to a more modern sockjs-1.5.x. 

In 0.3.4, the EventStream client code decoded the data with `unescape` (which does not err on unescaped `%` symbols). 
https://github.com/sockjs/sockjs-client/blob/0c70698bddcfab826c7b241ed709f69b5b0d41f7/lib/trans-receiver-eventsource.js#L12-L15

In sockjs-1.5.x, data is decoded with `decodeURI`, which errs on unescaped `%` symbols.
https://github.com/sockjs/sockjs-client/blob/71876b30849299255f34131af6474d959d61cbb2/lib/transport/receiver/eventsource.js#L19-L22

```javascript
unescape('%')
# => '%'
decodeURI('%')
# => URI error
```

This problem can be seen using the `webecho` example when modified so it only uses the `eventsource` or `iframe-eventsource` protocol.

```javascript
// Update the SockJS initialization in
// https://github.com/igm/sockjs-go/blob/master/examples/webecho/web/app.js
// No other modifications are necessary.

// options usage example
var options = {
		debug: true,
		devel: true,
                transports: ["eventsource"]
};
```

Visit the echo app and send the `%` character. This causes an error in the JS console after the client receives the message:

```
"a[\"%\"]"
```

The message should be:

```
"a[\"%25\""
```

This problem exists both in v2 and v3.

**Comment by igm** [comment]
thanks @aronatkins I'm looking into it. Do you know which escaping rules should be used here? 
Would [url.PathEscape()](https://pkg.go.dev/net/url#PathEscape) be ok for this? https://play.golang.org/p/AvMtpUoeMfR

**Comment by aronatkins** [comment]
I'm trying to understand it myself, @igm. If we treat sockjs-node as the reference, it escapes:
https://github.com/sockjs/sockjs-node/blob/9efed2c754226b702eb468ef0643b316b91bf37f/lib/transport/eventsource.js#L13-L17

using the code:
https://github.com/sockjs/sockjs-node/blob/9efed2c754226b702eb468ef0643b316b91bf37f/lib/utils.js#L28-L40

This appears to escape ``%`` (always escaped) along with `'\r\n\x00' (added by the event source code).

I looked at [sockjs-ruby](https://github.com/sockjs/sockjs-ruby) along with a few other implementations and am not finding lots of escaping out there!

In case it's helpful, here's more about EventSource: https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events

**Comment by aronatkins** [comment]
I pursued a similar idea and tried to use `url.QueryEscape`, but that caused problems in downstream code. I'm playing with the following and it appears to work in some simple testing.

```go
type eventSourceFrameWriter struct{}

var escaper *strings.Replacer = strings.NewReplacer(
	"%", url.QueryEscape("%"),
	"\n", url.QueryEscape("\n"),
	"\r", url.QueryEscape("\r"),
	"\x00", url.QueryEscape("\x00"),
)

func (*eventSourceFrameWriter) write(w io.Writer, frame string) (int, error) {
	return fmt.Fprintf(w, "data: %s\r\n\r\n", escaper.Replace(frame))
}
```

https://play.golang.org/p/EGF5StgLr8F

**Comment by jcheng5** [comment]
These escaping rules (`[%\r\n\x00]`) make perfect sense to me; `\r` and `\n` are the two characters that aren't allowed to be part of EventStream event data (see https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream). `\x00` is technically a legal character in the event data, but it seems pretty dangerous to have a string with embedded nulls. And then `%` obviously needs to be escaped since it's being used as the escape character.

**Comment by FZambia** [comment]
@aronatkins thanks for discovering and fixing this. Such an unexpected issue. +1 to the suggested fix with with the limited number of characters escaped.

**Comment by igm** [comment]
thanks all and especially @aronatkins . I've merged the PR for `v3` and `v2`. Please let me know if there's anything else we could do related to this problem.
