### ISSUE TITLE
Raw Websocket endpoint

### ISSUE THREAD

**Issue by FZambia** [igm/sockjs-go#23]
Hello! First of all thanks for a great work on implementing SockJS server in Go.

I looked through code but have not found raw WebSocket endpoint - i.e. something like `ws://localhost:8000/echo/websocket` to use SockJS server without SockJS client.

Is this not implemented?

**Comment by mgutz** [comment]
It's an option. I haven't tried it though:

https://github.com/igm/sockjs-go/blob/v2/sockjs/handler.go#L59

**Comment by FZambia** [comment]
Hmm, but this is a websocket endpoint with session prefix i.e. for sockjs websocket transport. My question was about raw websocket endpoint

**Comment by igm** [comment]
SockJS does not provide raw WebSocket implementation. The option @mgutz is referring to is there to provide SockJS framing on top of WebSocket. But for raw WebSocket there are other libraries you can use, like http://godoc.org/github.com/gorilla/websocket or https://godoc.org/golang.org/x/net/websocket

**Comment by FZambia** [comment]
Yep, I know about websocket libraries. But look at `Connecting to SockJS without the client` part in SockJS-client [readme](https://github.com/sockjs/sockjs-client) It's saying:

> Any SockJS server complying with 0.3 protocol does support a raw WebSocket url. 
> ...
> You can connect any WebSocket RFC 6455 compliant WebSocket client to this url.

It's implemented in sockjs-node and sockjs-tornado and maybe in other server implementations too
It's very useful because it's then possible to communicate with application via Websockets from any language, device

**Comment by igm** [comment]
SockJS-Go is a library (not a server). So if you are creating a server and you plan to be compliant with 0.3 protocol, then add raw WebSocket handlers to your server application.

**Comment by igm** [comment]
Also check this: https://github.com/igm/sockjs-go/blob/v2/testserver/server.go
It is a test server used for sockjs protocol tests. It also shows how to add raw WebSocket to you own server implementation.

**Comment by fatih** [comment]
As a side note, we have a Sockjs client written in Go that can be used to communicate with Sockjs Servers. Over Websocket or XHR Polling. It's here: https://github.com/koding/kite/tree/master/sockjsclient 

We are using it successfully in production for a while. It doesn't have a separate repo but we are going to break it from the Kite repo into a separate library. However you can already `go get` it and use it in your own app. It's already an independent package.

**Comment by FZambia** [comment]
@igm thanks, got it

**Comment by FZambia** [comment]
Btw, just to be pedantic - readme of sockjs-go says that this is a server

**Comment by igm** [comment]
thanks @FZambia, let's make it clear in the readme, too.

**Comment by FZambia** [comment]
Sorry, me again with the same question. Let me tell a story why I need this raw endpoint.

I have a project called [Centrifuge](https://github.com/centrifugal/centrifuge) - it uses sockjs-tornado internally which has rawwebsocket endpoint built-in. So I have one handler to deal with SockJS connections and raw websocket connections. And now I migrating it to Go.

I tried to play with Go routers but had no success to make raw websocket endpoint available at `/connection/websocket` - all requests to it intercepted by SockJS handler which is set on `/connection`. In my case I can't just change `/connection/websocket` to another path (something like just `/websocket` for example) - to not break backwards compatibility. Btw sockjs-node has raw websocket endpoint on the [same address](https://github.com/sockjs/sockjs-node/blob/master/src/sockjs.coffee#L85). Yep I remember that you told that sockjs-go is just a library to build server - but I have not just found a way to integrate raw websocket endpoint to fit my needs.

So I've made a fork of this library and added support for raw websocket enpoint - [here is a comparison](https://github.com/igm/sockjs-go/compare/v2...centrifugal:v2) between branches - it seems to work. Is there any chance this can be merged into main repo (at least turned of by default) or I should support my own fork?

P.S. Btw, yesterday I run sockjs-go with sockjs 1.0 beta on client side - and it works perfectly - the only change needed was setting SockJSURL option to a new version so iframe transport had url to the same client version.

**Comment by igm** [comment]
thanks @FZambia  let me look at it more in detail before I respond

**Comment by igm** [comment]
I'm trying to understand the problem you are having with registering handler. I've created simple example here: https://play.golang.org/p/B7iS_waSiI
There's a sockjs handler registered to ```/connection/``` prefix and additionally using standard http handlers way I registered additional handler on ```/connection/websocket``` which could be a raw websocket implementation.

Could you please describe more in details the problem you encountered when registering additional handler on ```/connection/``` prefix?
Personally I prefer to accept all PRs, so I'm quite positive about merging your pull request as well, but let me understand first the purpose of this change. And also I'd like to be able to replicate the issue you have with handlers registration.

**Comment by FZambia** [comment]
hmm, yep, it works using native http mux mechanism. At moment I use httprouter (https://github.com/julienschmidt/httprouter) - and it's not possible to register websocket handler on `/connection/websocket` because of how httprouter works - it requires routes starting with different prefixes. Also I tried `pat` from Gorilla toolkit - and had no success. But it was quiet along ago and maybe I did something wrong with it - I'll try again. Also I don't have complex router logic - so maybe going with standard library mux will be a good solution.

So there could be only 2 advantages in having raw websocket endpoint built in - no need to implement raw websocket yourself and possibility to use one common handler for all connections without implementing sockjs.Session like interface to deal with raw websocket connection.

Anyway I'll try to play with routes and separate raw websocket handler and write back. Thanks for your helpful response!

**Comment by FZambia** [comment]
I got rid of httprouter and finally implemented raw websocket handler using default http mux - need some testing and refactoring but works! Thanks for your help - can't understand why I have not succeeded before. I think we can close this?

**Comment by igm** [comment]
thanks for the update @FZambia .We could think of some way of how to provide raw websockets, but make it optional. We could achieve this via composition, so that sockjs library as it is now is not affected. We could create some structure (similar to what you had to create in your project) that would add websocket handler to sockjs and also unify "session" and "websocket connection" interfaces so that only one handler function is needed. I'll think of it and if something useful comes out of it I'll share it here. 
For now we can keep this issue as "enhancement"

**Comment by cenkalti** [comment]
We have another use case for raw websockets. We would like to communicate with our SockJS server from an iOS app but there is no library for Swift. If sockjs-go can support raw websocket, I can use it directly from any platform without the need of a SockJS library.

Raw WebSocket support is definded in SockJS protocol: http://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html#section-130
So why not implement in igm/sockjs-go?

@igm would you accept a PR if I provide one?

**Comment by igm** [comment]
@cenkalti I'll definitely look at the PR if you provide one for raw websockets.

**Comment by cenkalti** [comment]
@igm I can work on tests if you are okay with the idea at #58

**Comment by cenkalti** [comment]
@igm What do you think about the PR?

**Comment by igm** [comment]
I was quite reluctant about integrating raw websockets into the library, but I see the PR and it looks good to me. If you add tests we can merge it into master. Thanks for your contribution. 
_I apologise for not being more responsive recently, I'm AFK most of the time._

**Comment by FZambia** [comment]
@igm @cenkalti can we also add an option to disable raw websocket handler? In my case I use my own.

**Comment by cenkalti** [comment]
@igm The tests are ready.
@FZambia I have added the option to disable raw WebSocket support.

**Comment by FZambia** [comment]
@cenkalti thanks! One more thing I am worry about is ping/pong. In case of SockJS Websocket we send "h" frame periodically and broken/stale connection [will be closed](https://github.com/igm/sockjs-go/blob/master/sockjs/websocket.go#L77) eventually as soon as `func (w *wsReceiver) sendFrame(frame string)` fails to write message into connection (though I am not sure it's 100% reliable but at least at practice I never noticed problems with this approach). Now with raw websocket "h" frames not sent - so maybe it's reasonable to add Gorilla's ping/pong related stuff? I.e [send ping](https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L116) and set [pong handler](https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L62)?

**Comment by igm** [comment]
thanks for the additions @cenkalti I'll go over it. I have one suggestion though, lets make the default option for raw WebSocket to be false (disabled) to be backwards compatible.

**Comment by cenkalti** [comment]
@FZambia I have changed the receiver implementation to send websocket's ping message when "h" frame is sent by the session. For pong messages there is nothing to be done because gorilla/websocket's default ping handler sends "pong" messages automatically.

@igm I have made the default value `false` as you requested.

**Comment by FZambia** [comment]
@cenkalti also looks like we should support sending close frame with status and reason for raw websocket connections too so session `Close(status uint32, reason string) error` method worked the same way. Does it make sense?

**Comment by igm** [comment]
thanks @cenkalti for PR. I've merged changes into master. As ```RawWebsocket``` option is false in ```DefaultOptions``` I consider the change to be safe for projects importing sockjs-go/master.

**Comment by cenkalti** [comment]
@FZambia I have sent a new PR that address your issue: #59 However, I couldn't find a better way to implement this without changing `receiver` interface and breaking backwards compatibility.

**Comment by cenkalti** [comment]
Hi @igm. Can you review #59 please?
