### ISSUE TITLE
Interrupting Recv

### ISSUE THREAD

**Issue by YellowOrWhite** [igm/sockjs-go#35]
Thank you for nice lib.

I have implemented authentication wrapper that requires user to authenticate before he can do anything. I want to close a session that has not been authenticated for 5 seconds, so i added timeout to session handler. What i'm trying to understand is what happens when calling session Close while Recv blocked. Or if there is some better way to interrupt Recv?

**Comment by igm** [comment]
fixed in v3 by using `session.RecvCtx(ctx)`
