### ISSUE TITLE
GetSessionState/Request is not backwards-compatible

### ISSUE THREAD

**Issue by aronatkins** [igm/sockjs-go#37]
The `GetSessionState` method was added to `sockjs.Session` as of #36. This changed the interface on the stable `v2` tag.

**Comment by aronatkins** [comment]
Looks like #20 was also merged into `v2` again, meaning the `sockjs.Request` is also an interface change.

**Comment by aronatkins** [comment]
https://github.com/igm/sockjs-go/commit/6e45ce91cbd4775a3e9207e466062aacb012a699 needs to be reverted as well because that's what introduced `GetSessionState`. #36 simply made `GetSessionState` return a public type.

**Comment by aronatkins** [comment]
Workaround: use SHA 0410e9d7dff17ec69ad9aa284241cda30e4af9b2

**Comment by igm** [comment]
I am terribly sorry for this mess. I reverted back v2 to SHA as you suggested. I messed up with the merge of those PRs, effectively taking not only suggested PRs but everything from the remote repos. On top of that #36 broke the contract which should not go into v2 at all. My bad in this, sorry again.

**Comment by aronatkins** [comment]
Thanks for jumping on this. I am vendoring against that SHA for now and everything is good. I'll look into switching back to v2 directly later today.

**Comment by aronatkins** [comment]
Confirmed that v2 exposes the stable API again.
