### ISSUE TITLE
Avoiding using mutex for prefixRegex

### ISSUE THREAD

**Issue by mariokostelac** [igm/sockjs-go#40]
`handler.go` has a global map for compiled regexes.

Can we change it to compile regex upfront and attach it to the handler itself?
There are several benefits:
- it avoids using mutex for every session parsing. High throughput systems will be thankful for having one fewer lock
- we are not using global map and we do not have a memory leak. We never remove these compiled regexes from that global map. I doubt somebody will have increasing number of handler with different prefixes, but it's nice to have it done the right way.

I am happy to take this one if there are not some reasons that would blow my story away.

**Comment by igm** [comment]
thanks for the review @mariokostelac I agree this part of code can be improve. Please do take this, I'll be more than happy if this part of code improves.

**Comment by igm** [comment]
fixed in v3
