### ISSUE TITLE
Data race issue found in session.go: GetSessionState()

### ISSUE THREAD

**Issue by xiaoxiaoyijian** [igm/sockjs-go#42]
Hello,

I met a data race issue when I used the master branch in my code.

Related code in file: session.go
func (s *session) GetSessionState() sessionState { return s.state }

Could you please add s.Lock()/s.Unlock for this method? Or change the sync.Mutex to sync.RWMutex, and something like follow:
func (s *session) GetSessionState() sessionState {
    s.RLock()
    defer s.RUnlock() 
    return s.state
}

Thanks a lot.

**Comment by igm** [comment]
thanks @xiaoxiaoyijian for pointing this out

**Comment by xiaoxiaoyijian** [comment]
thanks a lot.
