### ISSUE TITLE
Is there a way to get the clients IP?

### ISSUE THREAD

**Issue by prawnsalad** [igm/sockjs-go#44]
I'm using v2 and looked around the source but I can't seem to find anything to grab the request or clients IP from a sockjs.Session instance?

**Comment by derlaft** [comment]
It seems that this functionality is only in master branch (Session.Request() method)

**Comment by igm** [comment]
I confirm what @derlaft stated, http.Request is accessible from Session in master branch https://github.com/igm/sockjs-go/blob/master/sockjs/sockjs.go#L10 not in v2 https://github.com/igm/sockjs-go/blob/v2/sockjs/sockjs.go 

This change affects the API so it cannot be merged into v2 (see #20)
