### ISSUE TITLE
Check if session is active

### ISSUE THREAD

**Issue by herkyl** [igm/sockjs-go#46]
How do I check if the session is active, and if it's impossible what is the workaround for this?

**Comment by igm** [comment]
In v2 it is not possible, so please use master branch and GetSessionState() function on Session:
https://github.com/igm/sockjs-go/blob/master/sockjs/sockjs.go#L18
Session states are defined here:
https://github.com/igm/sockjs-go/blob/master/sockjs/session.go#L16:L23
