### ISSUE TITLE
Add context support in the socket session

### ISSUE THREAD

**Issue by fivegreenapples** [igm/sockjs-go#64]
I was wondering whether you'd accept a pull request for some sort of context support in the socket session. Or at least some way of being notified of the session's end.

My use case is that sometimes an incoming websocket message kicks off a long running process. If the socket session dies, I'd like to cancel that process. I tried to pass session.Request().Context() down the line but now realise this doesn't work in fallback modes as session.Request() is only the _first_ request.

I hope I have explained myself clearly enough!

**Comment by igm** [comment]
I agree, it makes sense @fivegreenapples
