### ISSUE TITLE
CORS errors when trying to connect sockjs server from a local (file://) resource

### ISSUE THREAD

**Issue by UltraNemesis** [igm/sockjs-go#75]
PR #73 broke the ability to connect to a sockjs server based on this library from a html page launched as a local resource (file://) without use of web server.

This looks to be due to the addition of the check for incoming origin header "null" and then changing it to *. Earlier, when origin from client side is null, Access-Control-Allow-Origin was also set to "null" . But since its changed to *, Chrome does not allow it as a match for Origin "null"

I understand that sending "null" as allowed origin is not a good idea, but is there an alternative way get sockjs working form file:// resources. There are situations where we launch a html directly without web server.

**Comment by UltraNemesis** [comment]
This is the cors handler in sockjs-node

https://github.com/sockjs/sockjs-node/blob/14a5c3cf097126bde74436d001816c53a0593d43/src/trans-xhr.coffee#L63

The node version returns Access-Control-Allow-Origin as "null" when Origin sent is "null". So sockjs works from HTML loaded directly using file://

**Comment by igm** [comment]
Could you please describe more in details the problem? I tried some examples myself (e.g. https://gist.github.com/igm/2a817d075012637ee22df2ba40aaa710) but I probably don't understand your scenario.

**Comment by UltraNemesis** [comment]
Your sample is using a old version of sock.js client which didn't have proper CORS handling. 

Switch to the latest version of the library (1.3.0) by changing the reference to below

[https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js](https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js
)


After that, try opening the index html directly without hosting it on a web server

You will get a CORS error.

> Access to XMLHttpRequest at 'http://localhost:8080/echo/info?t=1564998064299' from origin 'null' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

This scenario used to work previously because when origin goes as "null" from the client side, sockjs-go responding with Access-Control-Allow-Origin : null. Now it responds with * which is not considered a match for origin "null"

**Comment by igm** [comment]
Thanks. The change was made on purpose in the code so that server does not return `null` in ` Access-Control-Allow-Origin` (see also https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null) . If sockjs-node implementation responds with `null` probably they should fix it, too.

There's a flag in chrome that lets you override the constraint `--allow-file-access-from-files`. Have you tried using Chrome browser with that flag?

**Comment by UltraNemesis** [comment]
I understand the reason for the change, but this breaks the ability to connect to the sockjs server from a local HTML file. There are genuine production use scenarios HTML content is loaded without web server.

For instance, Phonegap/Cordova apps have had been embedding HTML/JS files into the hybrid apps to improve performance.

Apple has also lately been rejecting hybrid apps that load HTML5 games from a remote web server based on the reasoning that functionality of the app is being controlled remotely without going though the app review process. The only solution acceptable to them currently for HTML5 games is to embed the HTML/JS content into the app bundle and to hit a remote server only for API/messaging. The present implementation would fail these scenarios.

Please consider exposing a flag in options to control Local File access or expose the corsHandler function outside so that developer can define his own custom behavior.

Also, to be honest, I don't see the real utility of this change for a socket server. It makes sense for regular web servers to put in CORS filters to prevent embedding or referencing their content in other unauthorized websites, but for sockjs server, that doesn't make a lot of sense. For example, I can connect to the server form a native client as well where CORS filter would be completely meaningless.

**Comment by igm** [comment]
I'm fine with having a flag for this with default behaviour like it is now. So if possible please send a PR and I'll merge it.
