### ISSUE TITLE
CDN for sockjs-0.3.min.js is already gone.

### ISSUE THREAD

**Issue by shu-mutou** [igm/sockjs-go#89]
Please release following commit as soon as possible.
https://github.com/igm/sockjs-go/commit/90eb0f5602c83cff38afce1a7fc92abae7b4b140#diff-59e9f77255aa4b5204cb9e9fcf9aa058

**Comment by shu-mutou** [comment]
latest release v2.0.1 does not include it.

**Comment by shu-mutou** [comment]
Could you fix also https://github.com/igm/sockjs-go/blob/v2_to_go_modules/sockjs/options.go#L57 ?

**Comment by igm** [comment]
fixed in v2.1.0

**Comment by shu-mutou** [comment]
Thank you so much!!! 🎉
