### ISSUE TITLE
Tag for v3

### ISSUE THREAD

**Issue by FZambia** [igm/sockjs-go#91]
Hello @igm !

Noticed that recently you did migration to v3. I believe that it was rather painful experience due to how go.mod works with dependencies > v2, glad you managed to do it pushing this library to an actual stack 👍

Just tried to introduce v3 dependency:

```
$ go mod init test_sockjs
go: creating new go.mod: module test_sockjs

$ go get github.com/igm/sockjs-go/v3/sockjs
go: downloading github.com/igm/sockjs-go v2.0.1+incompatible
go: downloading github.com/igm/sockjs-go/v3 v3.0.0-20200426155823-50a65008b72f
go: found github.com/igm/sockjs-go/v3/sockjs in github.com/igm/sockjs-go/v3 v3.0.0-20200426155823-50a65008b72f

$ cat go.mod
module test_sockjs

go 1.14

require github.com/igm/sockjs-go/v3 v3.0.0-20200426155823-50a65008b72f // indirect
```

I suppose `v3.0.0` tag for v3 required so go.mod can use dependency without pointing to exact commit.

**Comment by igm** [comment]
The main change in `v3` is a removal of `Session` interface which should provide more flexibility for future additions without breaking backwards compatibility. `Session` was aliased to `*session` struct, but as a side effect there was a problem in godoc which is described here (together with a possible fix): https://github.com/igm/sockjs-go/pull/92

I'll give it another look before merging to be sure it works fine as expected. If you find a moment @FZambia  please take look at the `v3` if there's anything that would required fixing before tagging it to `v3.0.0`

My original idea was also to fix https://github.com/igm/sockjs-go/issues/45 and https://github.com/igm/sockjs-go/issues/64 before tagging with `v3.0.0`

**Comment by FZambia** [comment]
Got it, will try to look

**Comment by igm** [comment]
tagged with `v3.0.0`
